--- 
- hosts: 172.31.20.61
  become: yes
  tasks: 
  - name: I want to execute Linux command directely by playbook
    command: hostname -f 
    register: myresult

  - name: I want to display my first task result 
    debug: 
     msg: "{{myresult}}" 

  - name: Instal  tree 
    apt:
     name: tree 
     state: present 
    when: myresult.stderr =="" 

  - name: Install git 
    apt: 
     name: git 
     state: present 
    when: myresult.stderr !=""
  