--- 
- name: copy tomcat uesr file into ansible nodes side
  template:
   src: templates/mytomcatuser.j2
   dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy context  file into ansible nodes side 
  template: 
   src: templates/mycontext.j2
   dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy host context file into ansible nodes side 
  template: 
   src: templates/myhostcontext.j2
   dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml